### ISSUE TITLE
Android Gradle plugin version

### ISSUE THREAD

**Issue by OSHeden** [Donnnno/candybar-foss#10]
Hello,
I'm testing this fork for the first time.
There's a huge gap between the version of the "original" Candybar and this fork (8.0.1 vs 7.1.3).

![image](https://github.com/Donnnno/candybar-foss/assets/26502373/b9d9de94-44fb-4563-90de-7e1fd737f97b)

Why do you update this part?
Thank you.

**Comment by Donnnno** [comment]
Hey, the main candybar repo is also on 8.01: https://github.com/zixpo/candybar/blob/main/build.gradle

I have no idea why, but my best guess would be: newer is better, right?

**Comment by OSHeden** [comment]
I agree that newer is better. Your fork still uses 7.1.3 (very old version). That's why I'm asking :)

**Comment by Donnnno** [comment]
ohh sorry, I got it wrong, I looked here, and it seems like 8.0.1
https://github.com/Donnnno/candybar-foss/blob/main/build.gradle

**Comment by Donnnno** [comment]
Should be updated now: 
forgot to update the sample repo. 

https://github.com/Donnnno/candybar-foss-sample

**Comment by OSHeden** [comment]
All good, thanks for the quick support.

**Comment by Donnnno** [comment]
No problem! Thanks for pointing it out, I tend to forget the sample repo sometimes. Just let me know if you need more help :)

**Comment by OSHeden** [comment]
@Donnnno Error with the new sample version:
![image](https://github.com/Donnnno/candybar-foss/assets/26502373/203e08e8-2877-4459-9d36-0f706e7633ea)

**Comment by Donnnno** [comment]
Let me check :)

**Comment by Donnnno** [comment]
It builds for me again with the latest fixes, does it work for you?

**Comment by OSHeden** [comment]
Not yet :)
![image](https://github.com/Donnnno/candybar-foss/assets/26502373/ec5deb06-98db-4ef4-aaf2-9c58fc55fc1a)

**Comment by Donnnno** [comment]
You can update these lines:
https://github.com/Donnnno/candybar-foss-sample/commit/5c9540dd7c69026ab92bfac0d2d34c67655d6adc

**Comment by OSHeden** [comment]
Another attempt :)
````
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.github.Donnnno.candybar-foss:library:3.17.4] /home/arnaud/.gradle/caches/transforms-3/8162ae88b576a5332ab76c602ade7b9e/transformed/jetified-library-3.17.4/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="candybar.lib" to force usage (may lead to runtime failures)
````

**Comment by OSHeden** [comment]
Sorry... Just seen that I created the issue in the wrong repo...

**Comment by Donnnno** [comment]
Ah no worries, is everything working now?

**Comment by OSHeden** [comment]
Yep. I just installed the app on my phone. I'll do additional tests tomorrow.
Nice to have this fork!

**Comment by Donnnno** [comment]
Great to hear that!
